import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# 1. Load the dataset generated by Module 1 & 2
dataset_path = "build/features_dataset.csv"
print(f"[*] Loading training dataset from: {dataset_path}")
df = pd.read_csv(dataset_path)

# 2. Separate Features (X) and Target Risk Score (y)
features = [
    "Block_Count",
    "Complexity",
    "Inst_Count",
    "Loop_Depth",
    "Has_Crypto",
    "String_Entropy"
]
target = "Target Risk Score"

X = df[features]
y = df[target]

print(f"[*] Loaded {len(df)} sample functions (Benign & Sensitive)")
print(f"[*] Extracted {len(features)} feature parameters for supervision.\n")

# 3. Split into 80% Training and 20% Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# 4. Train the Random Forest Regressor Model
print("[*] Training Random Forest Regressor (100 Decision Trees)...")
model = RandomForestRegressor(n_estimators=100, random_state=42, max_depth=10)
model.fit(X_train, y_train)

# 5. Evaluate the Model on Unseen Test Data
predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("\n=======================================================")
print("          ML MODEL EVALUATION RESULTS & METRICS        ")
print("=======================================================")
print(f"  * Total Dataset Size    : {len(df)} functions")
print(f"  * Test Set Validation   : {len(y_test)} unseen functions")
print(f"  * Mean Squared Error    : {mse:.6f} (Low error is better)")
print(f"  * R² Accuracy Score     : {r2 * 100:.2f}% (Variance explained)")
print("-------------------------------------------------------")
print("          FEATURE IMPORTANCE (WHAT THE AI VALUED)      ")
print("-------------------------------------------------------")

importances = model.feature_importances_
for col, imp in sorted(zip(features, importances), key=lambda x: x[1], reverse=True):
    print(f"  * {col:<20}: {imp * 100:.2f}%")
print("=======================================================\n")
print("[+] Model successfully validated! Ready for academic presentation.")
